[package]
name = "rs_vocab"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
dirs = "6.0.0"
rand = "0.9.2"
ratatui = "0.29.0"
serde = {version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
text_io = "0.1.13"
